### ISSUE TITLE
Risolvimi sono una piccola bollicina nell'aria 

### ISSUE THREAD

**Issue by LastHub** [blackninja22/Prove-github#4]
Se ne sei capace

**Comment by manuelagnelli** [comment]
arrivo

**Comment by alfonsomela** [comment]
subito !!11!!11 xoxoxxoxo :100: :1st_place_medal:

**Comment by LastHub** [comment]
`

> [Troppo innocente](https://www.youtube.com/watch?v=KmXEOLlX-Hk)

`
